#!/usr/bin/env bash
PASS_DIR=$HOME/.password-store
i=1
n_items=$(find "$PASS_DIR" -name "*.gpg" -type f | wc -l | tr -d " ")
while IFS= read -r -d '' f; do
    echo -n "Processed: $i/$n_items	"
    n="$(echo -n "${f##$PASS_DIR/}" | sed 's/.gpg//')"
    sha1=$(pass show "$n" | tr -d '\n' | shasum -a 1 | awk '{print $1}')
    result=$(curl https://api.pwnedpasswords.com/range/"${sha1:0:5}" 2>/dev/null | grep -i "${sha1:5:35}")
    if [ -n "$result" ]; then
        echo "PWNED: $n, count ${result##*:}"
    else
        echo -ne "\r"
    fi
    ((i++))
done < <(find "$PASS_DIR" -name "*.gpg" -type f -print0)
